#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : netlabel_tools
Version  : 0.30.0
Release  : 1
URL      : https://github.com/netlabel/netlabel_tools/releases/download/v0.30.0/netlabel_tools-0.30.0.tar.gz
Source0  : https://github.com/netlabel/netlabel_tools/releases/download/v0.30.0/netlabel_tools-0.30.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: netlabel_tools-bin = %{version}-%{release}
Requires: netlabel_tools-license = %{version}-%{release}
Requires: netlabel_tools-man = %{version}-%{release}
Requires: netlabel_tools-services = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
NetLabel Tools: A Library and Management Tool for the Linux NetLabel Subsystem
==============================================================================
https://github.com/netlabel/netlabel_tools

%package bin
Summary: bin components for the netlabel_tools package.
Group: Binaries
Requires: netlabel_tools-license = %{version}-%{release}
Requires: netlabel_tools-services = %{version}-%{release}

%description bin
bin components for the netlabel_tools package.


%package license
Summary: license components for the netlabel_tools package.
Group: Default

%description license
license components for the netlabel_tools package.


%package man
Summary: man components for the netlabel_tools package.
Group: Default

%description man
man components for the netlabel_tools package.


%package services
Summary: services components for the netlabel_tools package.
Group: Systemd services

%description services
services components for the netlabel_tools package.


%prep
%setup -q -n netlabel_tools-0.30.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551224248
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1551224248
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netlabel_tools
cp LICENSE %{buildroot}/usr/share/package-licenses/netlabel_tools/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/netlabel-config
/usr/bin/netlabelctl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netlabel_tools/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/netlabel-config.8
/usr/share/man/man8/netlabelctl.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/netlabel.service
